# Generated by Django 4.0.4 on 2022-04-22 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='data de  publicacao')),
                ('location', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
                ('more_details', models.CharField(max_length=500)),
                ('max_tickets', models.IntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventNation.organizer')),
            ],
        ),
    ]
